/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#9b0044',
        'primary-container': '#c2185b',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffd9df',
        'primary-fixed': '#ffd9df',
        'primary-fixed-dim': '#ffb1c2',
        'on-primary-fixed': '#3f0018',
        'on-primary-fixed-variant': '#8f003f',
        secondary: '#6b5a60',
        'secondary-container': '#f4dce4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#716066',
        'secondary-fixed': '#f4dce4',
        'secondary-fixed-dim': '#d7c1c8',
        'on-secondary-fixed': '#25181e',
        'on-secondary-fixed-variant': '#524249',
        tertiary: '#911856',
        'tertiary-container': '#b1346f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffd9e4',
        'tertiary-fixed': '#ffd9e4',
        'tertiary-fixed-dim': '#ffb0cc',
        'on-tertiary-fixed': '#3e0020',
        'on-tertiary-fixed-variant': '#890f50',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#594045',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'inverse-primary': '#ffb1c2',
        outline: '#8d6f75',
        'outline-variant': '#e1bec4',
        'surface-tint': '#b90c55',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
      boxShadow: {
        luminous: '0 10px 30px -10px rgba(194, 24, 91, 0.08)',
        'luminous-md': '0 4px 20px -2px rgba(194, 24, 91, 0.08)',
        'luminous-lg': '0 8px 30px 0 rgba(194, 24, 91, 0.15)',
      },
      animation: {
        'slow-spin': 'spin 20s linear infinite',
        'very-slow-spin': 'spin 30s linear infinite',
      },
    },
  },
  plugins: [],
};
